require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/links", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Link. As you add validations to Link, be sure to
  # adjust the attributes here as well.

  let(:valid_attributes) { FactoryBot.build(:link).attributes }

  let(:invalid_attributes) { FactoryBot.build(:invalid_link).attributes }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::LinksController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {:Authorization => "Token token=#{Rails.application.credentials.token}"}
  }

  # before(:each) do
  #   host! "lvh.me"
  # end

  describe "GET /index" do
    it "renders a successful response" do
      Link.create! valid_attributes
      get api_v1_links_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      link = Link.create! valid_attributes
      get api_v1_link_url(link), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Api::V1::Link" do
        expect {
          post api_v1_links_url,
               params: { link: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Link, :count).by(1)
      end

      it "renders a JSON response with the new api/v1_link" do
        post api_v1_links_url,
             params: { link: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Api::V1::Link" do
        expect {
          post api_v1_links_url,
               params: { link: invalid_attributes }, as: :json
        }.to change(Link, :count).by(0)
      end

      it "renders a JSON response with errors for the new api/v1_link" do
        post api_v1_links_url,
             params: { link: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) { FactoryBot.build(:link, url: 'https://uol.com.br', slug: 'uol').attributes }

      it "updates the requested api/v1_link" do
        link = Link.create! valid_attributes
        patch api_v1_link_url(link),
              params: { link: new_attributes }, headers: valid_headers, as: :json
        link.reload
        expect(link.url).to eq('https://uol.com.br')
        expect(link.slug).to eq('uol')
        expect(link.short).to eq("#{Rails.application.credentials.host}/#{link.slug}")
      end

      it "renders a JSON response with the api/v1_link" do
        link = Link.create! valid_attributes
        patch api_v1_link_url(link),
              params: { link: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the api/v1_link" do
        link = Link.create! valid_attributes
        patch api_v1_link_url(link),
              params: { link: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested api/v1_link" do
      link = Link.create! valid_attributes
      expect {
        delete api_v1_link_url(link), headers: valid_headers, as: :json
      }.to change(Link, :count).by(-1)
    end
  end
end
